/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CidadePodeFazer;
import controller.Jogador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nortton
 */
public class TelaCidade extends javax.swing.JFrame {

    TelaCidadeLoteria telaCidadeLoteria;
    Main telaAnterior;
    Jogador jogador;
    int sorte;
    
    CidadePodeFazer[] vetCidadePodeFazer;
    ArrayList<CidadePodeFazer> vetAux;
    CidadePodeFazer cidadePodeFazer;
    
    
    public TelaCidade(Main telaAnt, Jogador jog, int sor, CidadePodeFazer[] vetorCid) {
        initComponents();
        
        telaAnterior = telaAnt;
        jogador = jog;
        vetCidadePodeFazer = vetorCid;
        sorte = sor;
        
        TelaCidade.this.setLocationRelativeTo(null);
        TelaCidade.this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRestaurante = new javax.swing.JButton();
        btnHotel = new javax.swing.JButton();
        btnParque = new javax.swing.JButton();
        btnLoterica = new javax.swing.JButton();
        btnFaculdade = new javax.swing.JButton();
        btnTrabalhar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cbxFazer = new javax.swing.JComboBox<>();
        lblTempoNecessario = new javax.swing.JLabel();
        lblInteligenciaNecessaria = new javax.swing.JLabel();
        lblAltera = new javax.swing.JLabel();
        lblFome = new javax.swing.JLabel();
        lblSono = new javax.swing.JLabel();
        lblNecessidades = new javax.swing.JLabel();
        lblHigiene = new javax.swing.JLabel();
        lblSocial = new javax.swing.JLabel();
        lblDiversão = new javax.swing.JLabel();
        lblInteligencia = new javax.swing.JLabel();
        lblCustoValor = new javax.swing.JLabel();
        lblLucroValor = new javax.swing.JLabel();
        lblSaldoValor = new javax.swing.JLabel();
        btnProsseguir = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        lblCusto = new javax.swing.JLabel();
        lblLucro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ir Para Cidade");

        btnRestaurante.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnRestaurante.setText("Restaurante");
        btnRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauranteActionPerformed(evt);
            }
        });

        btnHotel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHotel.setText("Hotel");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });

        btnParque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnParque.setText("Parque");
        btnParque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParqueActionPerformed(evt);
            }
        });

        btnLoterica.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLoterica.setText("Loteria");
        btnLoterica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLotericaActionPerformed(evt);
            }
        });

        btnFaculdade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFaculdade.setText("Faculdade");
        btnFaculdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaculdadeActionPerformed(evt);
            }
        });

        btnTrabalhar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTrabalhar.setText("Trabalhar");
        btnTrabalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrabalharActionPerformed(evt);
            }
        });

        cbxFazer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxFazer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-FAZER-" }));
        cbxFazer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFazerItemStateChanged(evt);
            }
        });

        lblTempoNecessario.setText("Tempo: 10 minutos");

        lblInteligenciaNecessaria.setText("Int. Necessária: 20");

        lblAltera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAltera.setText("Altera:");

        lblFome.setText("Fome: 0%");

        lblSono.setText("Sono: 0%");

        lblNecessidades.setText("Necessidades: 0%");

        lblHigiene.setText("Higiene: 0%");

        lblSocial.setText("Social: 0%");

        lblDiversão.setText("Diversão: 0%");

        lblInteligencia.setText("Inteligência: 0");

        lblCustoValor.setText("Valor: R$ 50,00");

        lblLucroValor.setText("Valor: R$ 50,00");

        lblSaldoValor.setText("R$ 50,00");

        btnProsseguir.setBackground(new java.awt.Color(204, 255, 204));
        btnProsseguir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });

        lblSaldo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSaldo.setText("Saldo:");

        lblCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCusto.setText("Custo:");

        lblLucro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLucro.setText("Lucro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxFazer, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTempoNecessario)
                            .addComponent(lblInteligenciaNecessaria))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAltera)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(lblNecessidades))
                                .addComponent(lblFome)
                                .addComponent(lblSono)
                                .addComponent(lblHigiene)
                                .addComponent(lblSocial)
                                .addComponent(lblDiversão)
                                .addComponent(lblInteligencia)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCusto)
                            .addComponent(lblCustoValor)
                            .addComponent(lblLucro)
                            .addComponent(lblLucroValor)
                            .addComponent(btnProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo)
                            .addComponent(lblSaldoValor)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnParque, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoterica, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFaculdade, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTrabalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoterica, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParque, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFaculdade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrabalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(cbxFazer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTempoNecessario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInteligenciaNecessaria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNecessidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHigiene)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSocial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDiversão)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblInteligencia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCusto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCustoValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLucro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLucroValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldoValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        carregarOpcoesCidade(btnHotel.getText());
    }//GEN-LAST:event_btnHotelActionPerformed

    private void btnLotericaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLotericaActionPerformed
        carregarOpcoesCidade(btnLoterica.getText());
    }//GEN-LAST:event_btnLotericaActionPerformed

    private void btnRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauranteActionPerformed
        carregarOpcoesCidade(btnRestaurante.getText());
    }//GEN-LAST:event_btnRestauranteActionPerformed

    private void btnParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParqueActionPerformed
        carregarOpcoesCidade(btnParque.getText());
    }//GEN-LAST:event_btnParqueActionPerformed

    private void btnFaculdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaculdadeActionPerformed
        carregarOpcoesCidade(btnFaculdade.getText());
    }//GEN-LAST:event_btnFaculdadeActionPerformed

    private void btnTrabalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrabalharActionPerformed
        carregarOpcoesCidade(btnTrabalhar.getText());
    }//GEN-LAST:event_btnTrabalharActionPerformed

    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        if(cbxFazer.getSelectedItem().equals("Apostar")){
            telaCidadeLoteria();
        }
        if(jogador.getDinheiro()>=cidadePodeFazer.getCusto() && jogador.getNecessidades().getInteligencia()>=cidadePodeFazer.getInteligenciaNecessaria()){
            jogador.setDinheiro(jogador.getDinheiro()-cidadePodeFazer.getCusto());
            jogador.setDinheiro(jogador.getDinheiro()+cidadePodeFazer.getPagamento());
            
            jogador.getNecessidades().setFome(retornarValoresValidos(jogador.getNecessidades().getFome()+cidadePodeFazer.getNecessidades().getFome()));
            jogador.getNecessidades().setSono(retornarValoresValidos(jogador.getNecessidades().getSono()+cidadePodeFazer.getNecessidades().getSono()));
            jogador.getNecessidades().setNecessidades(retornarValoresValidos(jogador.getNecessidades().getNecessidades()+cidadePodeFazer.getNecessidades().getNecessidades()));
            jogador.getNecessidades().setHigiene(retornarValoresValidos(jogador.getNecessidades().getHigiene()+cidadePodeFazer.getNecessidades().getHigiene()));
            jogador.getNecessidades().setSocial(retornarValoresValidos(jogador.getNecessidades().getSocial()+cidadePodeFazer.getNecessidades().getSocial()));
            jogador.getNecessidades().setDiversao(retornarValoresValidos(jogador.getNecessidades().getDiversao()+cidadePodeFazer.getNecessidades().getDiversao()));
            
            jogador.getNecessidades().setInteligencia(jogador.getNecessidades().getInteligencia()+cidadePodeFazer.getNecessidades().getInteligencia());
            
            lblSaldoValor.setText("R$: " + jogador.getDinheiro());
            telaAnterior.atualizarVetores(jogador, -1, null, null, null, null);
            telaAnterior.alterarHUB();
        }else{
            JOptionPane.showMessageDialog(TelaCidade.this, "Dinheiro ou inteligencia necessaria insuficiente");
        }
    }//GEN-LAST:event_btnProsseguirActionPerformed

    public Byte retornarValoresValidos(int valor){
        if(valor<-120){
            return Byte.valueOf("-120");
        }else if(valor>120){
            return Byte.valueOf("120");
        }else{
            return Byte.valueOf(String.valueOf(valor));
        }
    }
    
    private void cbxFazerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFazerItemStateChanged
        carregarAlteracoesDaAcao(evt.getItem().toString());
    }//GEN-LAST:event_cbxFazerItemStateChanged

    public void carregarAlteracoesDaAcao(String fazer){
        if(!fazer.equals("-FAZER-")){
            int i=0;
            while(i<vetAux.size()){
                if(vetAux.get(i).getOpcao().equals(fazer)){
                    cidadePodeFazer = vetAux.get(i);
                    lblTempoNecessario.setText("Duração: " + cidadePodeFazer.getTempo() + " Minutos");
                    lblInteligenciaNecessaria.setText("Inteligência Necessária: " + cidadePodeFazer.getInteligenciaNecessaria());
                    lblFome.setText("Fome: " + cidadePodeFazer.getNecessidades().getFome() + "%");
                    lblSono.setText("Sono: " + cidadePodeFazer.getNecessidades().getSono()+ "%");
                    lblNecessidades.setText("Necessidades: " + cidadePodeFazer.getNecessidades().getNecessidades()+ "%");
                    lblHigiene.setText("Higiene: " + cidadePodeFazer.getNecessidades().getHigiene()+ "%");
                    lblSocial.setText("Social: " + cidadePodeFazer.getNecessidades().getSocial()+ "%");
                    lblDiversão.setText("Diversão: " + cidadePodeFazer.getNecessidades().getDiversao()+ "%");
                    lblInteligencia.setText("Inteligência: " + cidadePodeFazer.getNecessidades().getInteligencia()+ "%");
                    lblCustoValor.setText("R$: " + cidadePodeFazer.getCusto());
                    lblSaldoValor.setText("R$: " + jogador.getDinheiro());
                    lblLucroValor.setText("R$: " + cidadePodeFazer.getPagamento());
                }
                i++;
            }
        }
    }
    
    public void carregarOpcoesCidade(String local){    
        cbxFazer.removeAllItems();
        int i=0;
        int aux=0;
        vetAux = new ArrayList();
        while(i<vetCidadePodeFazer.length){
            if(vetCidadePodeFazer[i].getCidade().getNome().equals(local)){
                cbxFazer.addItem(vetCidadePodeFazer[i].getOpcao());
                vetAux.add(vetCidadePodeFazer[i]);
                aux++;
            }
            i++;
        }
    }
    
    public void telaCidadeLoteria(){
        telaCidadeLoteria = new TelaCidadeLoteria(jogador, sorte, telaAnterior);
        telaCidadeLoteria.setLocationRelativeTo(null);
        telaCidadeLoteria.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFaculdade;
    private javax.swing.JButton btnHotel;
    private javax.swing.JButton btnLoterica;
    private javax.swing.JButton btnParque;
    private javax.swing.JButton btnProsseguir;
    private javax.swing.JButton btnRestaurante;
    private javax.swing.JButton btnTrabalhar;
    private javax.swing.JComboBox<String> cbxFazer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAltera;
    private javax.swing.JLabel lblCusto;
    private javax.swing.JLabel lblCustoValor;
    private javax.swing.JLabel lblDiversão;
    private javax.swing.JLabel lblFome;
    private javax.swing.JLabel lblHigiene;
    private javax.swing.JLabel lblInteligencia;
    private javax.swing.JLabel lblInteligenciaNecessaria;
    private javax.swing.JLabel lblLucro;
    private javax.swing.JLabel lblLucroValor;
    private javax.swing.JLabel lblNecessidades;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoValor;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblSono;
    private javax.swing.JLabel lblTempoNecessario;
    // End of variables declaration//GEN-END:variables
}
