/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Catalogo;
import controller.CidadePodeFazer;
import controller.Comodo;
import controller.ItemPodeFazer;
import controller.Jogador;


public class TelaComodo extends javax.swing.JFrame {

    Main telaAnterior;
    Jogador jogador;
    int sorte;
    
    Catalogo[] vetCatalogo;
    CidadePodeFazer[] vetCidadePodeFazer;
    Comodo[] vetComodo;
    ItemPodeFazer[] vetItemPodeFazer;
    
    public TelaComodo(Main telaAnt, Jogador jog, int sor, Catalogo[] vetorCat, CidadePodeFazer[] vetorCid, Comodo[] vetorCom, ItemPodeFazer[] vetorItem) {
        initComponents();
        
        telaAnterior = telaAnt;
        jogador = jog;
        sorte = sor;
        vetCatalogo = vetorCat;
        vetCidadePodeFazer = vetorCid;
        vetComodo = vetorCom;
        vetItemPodeFazer = vetorItem;
        
        TelaComodo.this.setLocationRelativeTo(null);
        TelaComodo.this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSala = new javax.swing.JButton();
        btnQuarto = new javax.swing.JButton();
        btnCozinha = new javax.swing.JButton();
        btnGaragem = new javax.swing.JButton();
        btnBanheiro = new javax.swing.JButton();
        btnPiscina = new javax.swing.JButton();
        btnBiblioteca = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cbxUsar = new javax.swing.JComboBox<>();
        cbxFazer = new javax.swing.JComboBox<>();
        lblAltera = new javax.swing.JLabel();
        lblFome = new javax.swing.JLabel();
        lblSono = new javax.swing.JLabel();
        lblNecessidades = new javax.swing.JLabel();
        lblHigiene = new javax.swing.JLabel();
        lblSocial = new javax.swing.JLabel();
        lblDiversão = new javax.swing.JLabel();
        btnProsseguir = new javax.swing.JButton();
        lblDiversão1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comodos ");

        btnSala.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSala.setText("Sala");

        btnQuarto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnQuarto.setText("Quarto");

        btnCozinha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCozinha.setText("Cozinha");

        btnGaragem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGaragem.setText("Garagem");

        btnBanheiro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBanheiro.setText("Banheiro");

        btnPiscina.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPiscina.setText("Piscina");

        btnBiblioteca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBiblioteca.setText("Biblioteca");

        cbxUsar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxUsar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-USAR-" }));

        cbxFazer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbxFazer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-FAZER-" }));

        lblAltera.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAltera.setText("Altera:");

        lblFome.setText("Fome: 0%");

        lblSono.setText("Sono: 0%");

        lblNecessidades.setText("Necessidades: 0%");

        lblHigiene.setText("Higiene: 0%");

        lblSocial.setText("Social: 0%");

        lblDiversão.setText("Diversão: 0%");

        btnProsseguir.setBackground(new java.awt.Color(204, 255, 204));
        btnProsseguir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProsseguir.setText("Prosseguir");

        lblDiversão1.setText("Inteligência: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSala, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxFazer, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAltera)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFome)
                                        .addComponent(lblSono)
                                        .addComponent(lblHigiene)
                                        .addComponent(lblSocial)
                                        .addComponent(lblDiversão)
                                        .addComponent(lblDiversão1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblNecessidades, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSala, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPiscina, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxUsar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxFazer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnProsseguir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAltera)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblFome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSono)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNecessidades)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblHigiene)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSocial)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDiversão)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDiversão1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanheiro;
    private javax.swing.JButton btnBiblioteca;
    private javax.swing.JButton btnCozinha;
    private javax.swing.JButton btnGaragem;
    private javax.swing.JButton btnPiscina;
    private javax.swing.JButton btnProsseguir;
    private javax.swing.JButton btnQuarto;
    private javax.swing.JButton btnSala;
    private javax.swing.JComboBox<String> cbxFazer;
    private javax.swing.JComboBox<String> cbxUsar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAltera;
    private javax.swing.JLabel lblDiversão;
    private javax.swing.JLabel lblDiversão1;
    private javax.swing.JLabel lblFome;
    private javax.swing.JLabel lblHigiene;
    private javax.swing.JLabel lblNecessidades;
    private javax.swing.JLabel lblSocial;
    private javax.swing.JLabel lblSono;
    // End of variables declaration//GEN-END:variables
}
