/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Jogador;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nortton
 */
public class TelaCidadeLoteria extends javax.swing.JFrame {

    Jogador jogador;
    int sorte;
    Main telaAnterior;
    DefaultTableModel dtmNumerosSorteados;
    
    public TelaCidadeLoteria(Jogador jog, int sor, Main telaAnt) {
        jogador = jog;
        sorte = sor;
        telaAnterior = telaAnt;
        initComponents();
        lblSaldo.setText("Saldo: R$ " + String.valueOf(jogador.getDinheiro()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        spnN1 = new javax.swing.JSpinner();
        spnN2 = new javax.swing.JSpinner();
        spnN3 = new javax.swing.JSpinner();
        spnN4 = new javax.swing.JSpinner();
        spnN5 = new javax.swing.JSpinner();
        spnN6 = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jpRegra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnApostar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumSorteados = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        lblPremio = new javax.swing.JLabel();
        txtValorAposta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loteria");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Escolha 6 numeros para apostar:");

        lblSaldo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblSaldo.setText("Saldo: R$ 0,00");

        spnN1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        spnN2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        spnN3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        spnN4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        spnN5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        spnN6.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Valor da Aposta:");

        jpRegra.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("REGRA:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("0 Acerto: 0% retorno");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("1 Acerto: 25% retorno");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("2 Acertos:50% retorno");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("3 Acertos: 100% retorno");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("4 Acertos: 200% retorno");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("5 Acertos: 500% retorno");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("6 Acertos: 1000% retorno");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Retorno = Valor apostado +");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("a porcentagem correspondente");

        javax.swing.GroupLayout jpRegraLayout = new javax.swing.GroupLayout(jpRegra);
        jpRegra.setLayout(jpRegraLayout);
        jpRegraLayout.setHorizontalGroup(
            jpRegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(jpRegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRegraLayout.setVerticalGroup(
            jpRegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegraLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnApostar.setBackground(new java.awt.Color(0, 204, 51));
        btnApostar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnApostar.setText("APOSTAR!");
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        tblNumSorteados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sorteados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNumSorteados);

        lblPremio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPremio.setText("VOCÊ GANHOU: R$ 0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnApostar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValorAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jpRegra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPremio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnN1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnN2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnN3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnN4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnN5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnN6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSaldo))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnN6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpRegra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPremio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
        if(!txtValorAposta.getText().trim().isEmpty() && Double.valueOf(txtValorAposta.getText().trim())<=jogador.getDinheiro()){
            jogador.setDinheiro(jogador.getDinheiro()-Double.valueOf(txtValorAposta.getText()));
            
            dtmNumerosSorteados = (DefaultTableModel)tblNumSorteados.getModel();
            int n1, n2, n3, n4, n5, n6;
            n1 = Integer.valueOf(spnN1.getValue().toString());
            n2 = Integer.valueOf(spnN2.getValue().toString());
            n3 = Integer.valueOf(spnN3.getValue().toString());
            n4 = Integer.valueOf(spnN4.getValue().toString());
            n5 = Integer.valueOf(spnN5.getValue().toString());
            n6 = Integer.valueOf(spnN6.getValue().toString());
            int[] valores = new int[6];
            int[] sorteados = new int[6];
            int aux=0;
            int strike=0;
            valores[0]=n1;
            valores[1]=n2;
            valores[2]=n3;
            valores[3]=n4;
            valores[4]=n5;
            valores[5]=n6;
            while(aux<6){
                if(valores[aux]==n1)strike++;
                if(valores[aux]==n2)strike++;
                if(valores[aux]==n3)strike++;
                if(valores[aux]==n4)strike++;
                if(valores[aux]==n5)strike++;
                if(valores[aux]==n6)strike++;
                if(strike>=2)break;
                strike=0;
                aux++;
            }
            if(strike>=2){
                JOptionPane.showMessageDialog(TelaCidadeLoteria.this, "Numeros repetidos. escolha 6 numeros diferentes para apostar!");
            }else{
                aux=0;
                boolean flag=true;
                Random rand = new Random();
                int s1, s2, s3, s4, s5, s6;
                sorteados = new int[6];
                while(flag){
                    s1 = rand.nextInt(30) + 1;
                    s2 = rand.nextInt(30) + 1;
                    s3 = rand.nextInt(30) + 1;
                    s4 = rand.nextInt(30) + 1;
                    s5 = rand.nextInt(30) + 1;
                    s6 = rand.nextInt(30) + 1;

                    sorteados[0]=s1;
                    sorteados[1]=s2;
                    sorteados[2]=s3;
                    sorteados[3]=s4;
                    sorteados[4]=s5;
                    sorteados[5]=s6;

                    strike=0;

                    while(aux<6){
                        if(sorteados[aux]==s1)strike++;
                        if(sorteados[aux]==s2)strike++;
                        if(sorteados[aux]==s3)strike++;
                        if(sorteados[aux]==s4)strike++;
                        if(sorteados[aux]==s5)strike++;
                        if(sorteados[aux]==s6)strike++;
                        if(strike>=2)break;
                        strike=0;
                        aux++;
                    }

                    if(strike<2){
                        flag=false;
                    }
                }

                sorteados = calcularSorte(sorteados, valores);
                
                strike=0;
                aux=0;

                dtmNumerosSorteados.setNumRows(0);
                dtmNumerosSorteados.addRow(value(sorteados[0]));
                dtmNumerosSorteados.addRow(value(sorteados[1]));
                dtmNumerosSorteados.addRow(value(sorteados[2]));
                dtmNumerosSorteados.addRow(value(sorteados[3]));
                dtmNumerosSorteados.addRow(value(sorteados[4]));
                dtmNumerosSorteados.addRow(value(sorteados[5]));

                while(aux<6){

                    if(sorteados[aux]==valores[0])strike++;
                    if(sorteados[aux]==valores[1])strike++;
                    if(sorteados[aux]==valores[2])strike++;
                    if(sorteados[aux]==valores[3])strike++;
                    if(sorteados[aux]==valores[4])strike++;
                    if(sorteados[aux]==valores[5])strike++;

                    aux++;
                }
                System.out.println("Acertos: " + strike);
                calcularPremio(strike);
            }
        }else{
            JOptionPane.showMessageDialog(TelaCidadeLoteria.this, "Realize uma aposta minima ou dinheiro apostado insuficiente");
        }
    }//GEN-LAST:event_btnApostarActionPerformed
    
    public int[] calcularSorte(int[] sorteados, int[] valores){
        int ajuda=0;
        if(sorte>=100){
            ajuda=6;
            sorte-=100;
        }else if(sorte>=70){
            ajuda=3;
            sorte-=70;
        }else if(sorte>=30){
            ajuda=1;
            sorte-=30;
        }
        int aux=0, strike=0;
        while(ajuda>0){
            if(sorteados[aux]==valores[0])strike++;
            if(sorteados[aux]==valores[1])strike++;
            if(sorteados[aux]==valores[2])strike++;
            if(sorteados[aux]==valores[3])strike++;
            if(sorteados[aux]==valores[4])strike++;
            if(sorteados[aux]==valores[5])strike++;
            aux++;
        }
        return sorteados;
    }
    
    public void calcularPremio(int strike){
        double valorAposta = Double.valueOf(txtValorAposta.getText());
        double ApostaFracionada = valorAposta/100;
        double premio=0;
        switch(strike){
            case 0:premio = ApostaFracionada*0;break;
            case 1:premio = ApostaFracionada*25;break;
            case 2:premio = ApostaFracionada*50;break;
            case 3:premio = ApostaFracionada*100;break;
            case 4:premio = ApostaFracionada*200;break;
            case 5:premio = ApostaFracionada*500;break;
            case 6:premio = ApostaFracionada*1000;break;
        }
        lblPremio.setText("VOCÊ GANHOU: R$ " + premio +"(" + strike + ") ACERTOS");
        jogador.setDinheiro(jogador.getDinheiro()+premio);
        lblSaldo.setText("Saldo: R$ " + String.valueOf(jogador.getDinheiro()));
        telaAnterior.atualizarVetores(jogador, sorte, null, null, null, null);
        telaAnterior.alterarHUB();
    }
    
    public String[] value(int v){
        return new String[]{
            String.valueOf(v)
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpRegra;
    private javax.swing.JLabel lblPremio;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JSpinner spnN1;
    private javax.swing.JSpinner spnN2;
    private javax.swing.JSpinner spnN3;
    private javax.swing.JSpinner spnN4;
    private javax.swing.JSpinner spnN5;
    private javax.swing.JSpinner spnN6;
    private javax.swing.JTable tblNumSorteados;
    private javax.swing.JTextField txtValorAposta;
    // End of variables declaration//GEN-END:variables
}
