package controller;
// Generated 28/11/2018 04:55:57 by Hibernate Tools 4.3.1

import java.awt.Frame;

/**
 * Catalogo generated by hbm2java
 */
public class Catalogo implements java.io.Serializable {

    private Integer idCatalogo;
    private Comodo comodo;
    private Item item;
    private double custo;
    private byte possui;

    public Catalogo() {
    }

    public Catalogo(Comodo comodo, Item item, double custo, byte possui) {
       this.comodo = comodo;
       this.item = item;
       this.custo = custo;
       this.possui = possui;
       cadastrar();
    }
    
    private void cadastrar(){
        model.Inserir inserir = new model.Inserir();
        inserir.save(this);
    }
    
    public void atualizar(Catalogo c, Catalogo cat[]){
        model.Atualizar atualizar = new model.Atualizar();
        atualizar.update(c, cat);
    }
    
    public void deletar(){
        model.Deletar deletar= new model.Deletar();
        deletar.delete(this);
    }
    
    public Catalogo[] buscarCatalagos(){
        model.Buscar buscar = new model.Buscar();
        return buscar.buscarCatalogos("From Catalogo");
    }
    
    public String[] getCatalogo(){
        return new String[]{
            String.valueOf(idCatalogo),
            comodo.getNome(),
            item.getNome(),
            String.valueOf(custo)
        };
    }
   
    public Integer getIdCatalogo() {
        return this.idCatalogo;
    }
    
    public void setIdCatalogo(Integer idCatalogo) {
        this.idCatalogo = idCatalogo;
    }
    public Comodo getComodo() {
        return this.comodo;
    }
    
    public void setComodo(Comodo comodo) {
        this.comodo = comodo;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public double getCusto() {
        return this.custo;
    }
    
    public void setCusto(double custo) {
        this.custo = custo;
    }
    public byte getPossui() {
        return this.possui;
    }
    
    public void setPossui(byte possui) {
        this.possui = possui;
    }




}


