package controller;
// Generated 28/11/2018 04:55:57 by Hibernate Tools 4.3.1



/**
 * CidadePodeFazer generated by hbm2java
 */
public class CidadePodeFazer  implements java.io.Serializable {

    private Integer id;
    private Cidade cidade;
    private Necessidades necessidades;
    private String opcao;
    private double custo;
    private double pagamento;
    private int tempo;
    private int inteligenciaNecessaria;

    public CidadePodeFazer() {
    }

    public CidadePodeFazer(Cidade cidade, Necessidades necessidades, String opcao, double custo, double pagamento, int tempo, int inteligenciaNecessaria) {
       this.cidade = cidade;
       this.necessidades = necessidades;
       this.opcao = opcao;
       this.custo = custo;
       this.pagamento = pagamento;
       this.tempo = tempo;
       this.inteligenciaNecessaria = inteligenciaNecessaria;
       cadastrar();
    }
    
    private void cadastrar(){
        model.Inserir inserir = new model.Inserir();
        inserir.save(this);
    }
    
    public void atualizar(){
        model.Atualizar atualizar = new model.Atualizar();
        atualizar.update(this);
    }
    
    public void deletar(){
        model.Deletar deletar= new model.Deletar();
        deletar.delete(this);
    }
    
    public CidadePodeFazer[] buscarCidadePodeFazer(){
        model.Buscar buscar = new model.Buscar();
        return buscar.BuscarCidadesPodeFazer("From CidadePodeFazer");
    }
    
    public String[] getCidadePodeFazer(){
        return new String[]{
            opcao,
            cidade.getNome()
        };
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public Necessidades getNecessidades() {
        return this.necessidades;
    }
    
    public void setNecessidades(Necessidades necessidades) {
        this.necessidades = necessidades;
    }
    public String getOpcao() {
        return this.opcao;
    }
    
    public void setOpcao(String opcao) {
        this.opcao = opcao;
    }
    public double getCusto() {
        return this.custo;
    }
    
    public void setCusto(double custo) {
        this.custo = custo;
    }
    public double getPagamento() {
        return this.pagamento;
    }
    
    public void setPagamento(double pagamento) {
        this.pagamento = pagamento;
    }
    public int getTempo() {
        return this.tempo;
    }
    
    public void setTempo(int tempo) {
        this.tempo = tempo;
    }
    public int getInteligenciaNecessaria() {
        return this.inteligenciaNecessaria;
    }
    
    public void setInteligenciaNecessaria(int inteligenciaNecessaria) {
        this.inteligenciaNecessaria = inteligenciaNecessaria;
    }




}


