package controller;
// Generated 28/11/2018 04:55:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comodo generated by hbm2java
 */
public class Comodo  implements java.io.Serializable {


     private Integer idComodo;
     private String nome;
     private byte possui;
     private Set catalogos = new HashSet(0);

    public Comodo() {
    }

	
    public Comodo(String nome, byte possui) {
        this.nome = nome;
        this.possui = possui;
        cadastrar();
    }
    
    private void cadastrar(){
        model.Inserir inserir = new model.Inserir();
        inserir.save(this);
    }
    
    public void atualizar(Comodo c, Comodo[] comodo){
        model.Atualizar atualizar = new model.Atualizar();
        atualizar.update(c, comodo);
    }
    
    public void deletar(){
        model.Deletar deletar= new model.Deletar();
        deletar.delete(this);
    }
    
    public Comodo[] buscarComodos(){
        model.Buscar buscar = new model.Buscar();
        return buscar.buscarComodos("From Comodo");
    }
    
    public String[] getComodo(){
        return new String[]{
            nome
        };
    }
    
    public Comodo(String nome, byte possui, Set catalogos) {
       this.nome = nome;
       this.possui = possui;
       this.catalogos = catalogos;
    }
   
    public Integer getIdComodo() {
        return this.idComodo;
    }
    
    public void setIdComodo(Integer idComodo) {
        this.idComodo = idComodo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public byte getPossui() {
        return this.possui;
    }
    
    public void setPossui(byte possui) {
        this.possui = possui;
    }
    public Set getCatalogos() {
        return this.catalogos;
    }
    
    public void setCatalogos(Set catalogos) {
        this.catalogos = catalogos;
    }




}


