package controller;
// Generated 28/11/2018 04:55:57 by Hibernate Tools 4.3.1



/**
 * ItemPodeFazer generated by hbm2java
 */
public class ItemPodeFazer  implements java.io.Serializable {


     private Integer idFazer;
     private Item item;
     private Necessidades necessidades;
     private String opcao;
     private int tempo;

    public ItemPodeFazer() {
    }

    public ItemPodeFazer(Item item, Necessidades necessidades, String opcao, int tempo) {
       this.item = item;
       this.necessidades = necessidades;
       this.opcao = opcao;
       this.tempo = tempo;
       cadastrar();
    }
    
    private void cadastrar(){
        model.Inserir inserir = new model.Inserir();
        inserir.save(this);
    }
    
    public void atualizar(){
        model.Atualizar atualizar = new model.Atualizar();
        atualizar.update(this);
    }
    
    public void deletar(){
        model.Deletar deletar= new model.Deletar();
        deletar.delete(this);
    }
    
    public ItemPodeFazer[] buscarItemPodeFazer(){
        model.Buscar buscar = new model.Buscar();
        return buscar.BuscarItemPodeFazer("From ItemPodeFazer");
    }
    
    public String[] getItemPodeFazer(){
        return new String[]{
            opcao,
            item.getNome()
        };
    }
   
    public Integer getIdFazer() {
        return this.idFazer;
    }
    
    public void setIdFazer(Integer idFazer) {
        this.idFazer = idFazer;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Necessidades getNecessidades() {
        return this.necessidades;
    }
    
    public void setNecessidades(Necessidades necessidades) {
        this.necessidades = necessidades;
    }
    public String getOpcao() {
        return this.opcao;
    }
    
    public void setOpcao(String opcao) {
        this.opcao = opcao;
    }
    public int getTempo() {
        return this.tempo;
    }
    
    public void setTempo(int tempo) {
        this.tempo = tempo;
    }




}


