package controller;
// Generated 28/11/2018 04:55:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer idItem;
     private String nome;
     private Set itemPodeFazers = new HashSet(0);
     private Set catalogos = new HashSet(0);

    public Item() {
    }

	
    public Item(String nome) {
        this.nome = nome;
        cadastrar();
    }
    
    private void cadastrar(){
        model.Inserir inserir = new model.Inserir();
        inserir.save(this);
    }
    
    public void atualizar(){
        model.Atualizar atualizar = new model.Atualizar();
        atualizar.update(this);
    }
    
    public void deletar(){
        model.Deletar deletar= new model.Deletar();
        deletar.delete(this);
    }
    
    public Item[] buscarItens(){
        model.Buscar buscar = new model.Buscar();
        return buscar.BuscarItem("From Item");
    }
    
    public String[] getItem(){
        return new String[]{
            nome
        };
    }
    
    public Item(String nome, Set itemPodeFazers, Set catalogos) {
       this.nome = nome;
       this.itemPodeFazers = itemPodeFazers;
       this.catalogos = catalogos;
    }
   
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getItemPodeFazers() {
        return this.itemPodeFazers;
    }
    
    public void setItemPodeFazers(Set itemPodeFazers) {
        this.itemPodeFazers = itemPodeFazers;
    }
    public Set getCatalogos() {
        return this.catalogos;
    }
    
    public void setCatalogos(Set catalogos) {
        this.catalogos = catalogos;
    }




}


